import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Pflanzia",
  description: "Pflanzia Terms of Service — rules and responsibilities for using the platform.",
};

const sections = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content: `By accessing or using Pflanzia, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the service.`,
  },
  {
    id: "service",
    title: "2. Service Description",
    content: `Pflanzia provides AI-powered plant identification and care information. Results are generated by machine learning models and should be used as guidance, not as professional botanical advice. Always verify critical information (such as toxicity) through multiple sources before acting on it.`,
  },
  {
    id: "accounts",
    title: "3. User Accounts",
    content: `You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. Pflanzia reserves the right to terminate accounts that violate these terms.`,
  },
  {
    id: "prohibited",
    title: "4. Prohibited Use",
    content: `You agree not to:\n\n• Upload images that are illegal, offensive, or infringe on third-party rights\n• Attempt to reverse-engineer, scrape, or abuse the API\n• Use the service to train competing AI models\n• Impersonate other users or Pflanzia staff\n• Use automated systems to generate large volumes of identification requests`,
  },
  {
    id: "content",
    title: "5. User Content",
    content: `By uploading images to Pflanzia, you grant us a non-exclusive license to process those images for the purpose of providing the service. You retain ownership of your images. We will not use your images for advertising or share them publicly without your consent.`,
  },
  {
    id: "disclaimer",
    title: "6. Disclaimer of Warranties",
    content: `Pflanzia is provided "as is" without warranties of any kind, express or implied. We do not guarantee the accuracy, completeness, or reliability of any plant identification result. Use plant identification results at your own risk, especially for decisions related to consumption or toxicity.`,
  },
  {
    id: "liability",
    title: "7. Limitation of Liability",
    content: `To the fullest extent permitted by law, Pflanzia and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from use of the service, including but not limited to harm resulting from acting on incorrect plant identification results.`,
  },
  {
    id: "changes",
    title: "8. Changes to Terms",
    content: `We may update these Terms of Service from time to time. Continued use of the service after changes constitutes acceptance of the new terms. We will notify registered users of material changes by email.`,
  },
  {
    id: "contact",
    title: "9. Contact",
    content: `For questions about these terms, contact us at legal@pflanzia.app.`,
  },
];

const toc = sections.map((s) => ({ id: s.id, label: s.title }));

export default function TermsPage() {
  return (
    <div className="text-white">
      {/* Hero */}
      <section className="border-b border-gray-800 px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl">
          <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
          <p className="text-gray-500 text-sm">Last updated: June 1, 2026</p>
        </div>
      </section>

      {/* Content with sticky ToC */}
      <section className="px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-5xl flex gap-12 items-start">
          {/* Sticky ToC */}
          <aside className="hidden lg:block w-56 shrink-0 sticky top-24">
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-4">Contents</p>
            <nav className="space-y-2">
              {toc.map((item) => (
                <a
                  key={item.id}
                  href={`#${item.id}`}
                  className="block text-sm text-gray-500 hover:text-green-400 transition-colors leading-snug"
                >
                  {item.label}
                </a>
              ))}
            </nav>
          </aside>

          {/* Content */}
          <div className="flex-1 space-y-12 min-w-0">
            {sections.map((section) => (
              <div key={section.id} id={section.id}>
                <h2 className="text-xl font-bold text-white mb-4">{section.title}</h2>
                <div className="text-gray-400 leading-relaxed text-sm whitespace-pre-line">
                  {section.content}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
